parameters:
    site_directory: '%kernel.project_dir%/../../../site'

    text_size: 100
    angle: 0
    font: '/ubuntu.ttf'
    padding: 100
    signature: 'romanvesely.com'
    signature_size: 25
    width: 1200

    # colors
    background: [254, 255, 241] # light yellow
    foreground: [27, 116, 171] # blue
    signature: [140, 140, 140] # grey

services:
    _defaults:
        autowire: true
        bind:
            '$siteDirectory': '%site_directory%'
            '$size': '%text_size%'
            '$angle': '%angle%'
            '$width': '%width%'
            '$font': '%font%'

    Crazko\Site\SocialImages\:
        resource: '../*'
        public: true

    Crazko\Site\SocialImages\Image:
        autowire: false

    Crazko\Site\SocialImages\Text:
        autowire: false
