parameters:
    site_directory: '%kernel.project_dir%/../../../site'
    image:
        width: 1200
        padding: 100
        font: '/ubuntu.ttf'
        angle: 0
        size: 100
        signature: 'romanvesely.com'
        signatureSize: 25
    color:
        background: [254, 255, 241] # light yellow
        foreground: [27, 116, 171] # blue
        signature: [140, 140, 140] # grey

services:
    _defaults:
        autowire: true
        bind:
            '$siteDirectory': '%site_directory%'
            '$image': '%image%'
            '$color': '%color%'

    Crazko\Site\SocialImages\:
        resource: '../*'
        public: true

    Crazko\Site\SocialImages\Text:
        autowire: false
