parameters:
    site_directory: '%kernel.project_dir%/../../../site'
    signature_size: 25
    colors:
        background: [254, 255, 241] # light yellow
        foreground: [27, 116, 171] # blue
        signature: [140, 140, 140] # grey

services:
    _defaults:
        autowire: true
        bind:
            '$siteDirectory': '%site_directory%'

    Crazko\Site\SocialImages\:
        resource: '../*'
        public: true

    # Crazko\Site\SocialImages\PostsProvider:
    #     arguments:
    #         - '%site_directory%'
