language: php

php: 7.1

branches:
    only:
        - master

before_install:
  - npm i -g npm@6.1.0

install:
    - composer install
    - npm install

before_script:
    - composer check

script:
    - npm run build

deploy:
    provider: script
    script: bin/deploy
    skip_cleanup: true
    on:
        branch: master

notifications:
    email: false
